name: Sync Fork

on:
schedule:
- cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
workflow_dispatch: # 允许手动触发

jobs:
sync:
runs-on: ubuntu-latest
steps:
- name: Checkout the repository
uses: actions/checkout@v3
with:
persist-credentials: false

- name: Fetch changes from upstream
run: |
git config --global user.name 'MrSANGA'
git config --global user.email 'sangsi2008@gmail.com'
git remote add upstream https://github.com/go-gost/gost.git
git fetch upstream
git checkout main
git merge upstream/main
git push origin main
